package:
  name: azure-workload-identity-webhook
  version: 1.5.0
  epoch: 0
  description: Mutating webhook for Azure Workload Identity
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/Azure/azure-workload-identity
      tag: v${{package.version}}
      expected-commit: 350cb28ceab55d0696bef2077a1cc9dff368e982

  - uses: go/build
    with:
      packages: ./cmd/webhook
      output: manager
      ldflags: |-
        -X github.com/Azure/azure-workload-identity/pkg/version.BuildVersion=v${{package.version}}
        -X github.com/Azure/azure-workload-identity/pkg/version.BuildTime=$(date -u -d "@$SOURCE_DATE_EPOCH" +%Y-%m-%d-%H:%M)
        -X github.com/Azure/azure-workload-identity/pkg/version.VCSVersion=$(git rev-parse --short HEAD)
        -X github.com/Azure/azure-workload-identity/pkg/webhook.ProxyImageVersion=v${{package.version}}
        -X github.com/Azure/azure-workload-identity/pkg/webhook.ProxyImageRegistry=mcr.microsoft.com/oss/azure/workload-identity

subpackages:
  - name: ${{package.name}}-compat
    description: Compatibility symlink for ${{package.name}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"
          ln -s /usr/bin/manager "${{targets.contextdir}}/manager"
    test:
      pipeline:
        - runs: |
            stat /manager

update:
  enabled: true
  github:
    identifier: Azure/azure-workload-identity
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - openssl
        - curl
    environment:
      AZURE_TENANT_ID: "00000000-0000-0000-0000-000000000000"
  pipeline:
    - name: "Run manager and verify help output"
      runs: |
        manager --help
    - name: "Basic kwok cluster test"
      uses: test/kwok/cluster
    - name: "Verify webhook manager startup"
      uses: test/daemon-check-output
      with:
        setup: |
          kubectl create namespace azure-workload-identity-test
          kubectl get namespace azure-workload-identity-test

          # Create dummy certificates in /tmp
          echo "Creating dummy certificates..."
          openssl req -x509 -newkey rsa:2048 -keyout /tmp/tls.key -out /tmp/tls.crt -days 365 -nodes -subj "/CN=webhook.azure-workload-identity-test.svc"

          export AZURE_TENANT_ID="00000000-0000-0000-0000-000000000000"
        start: |
          manager \
            --disable-cert-rotation \
            --metrics-addr=:8082 \
            --health-addr=:8081 \
            --webhook-cert-dir=/tmp
        timeout: 15
        expected_output: |
          Starting metrics server
          Serving metrics server
          Starting webhook server
          Serving webhook server
          Registering webhook
        error_strings: |
          failed
          Failed
          error
          Error
        post: |
          curl -s http://localhost:8081/healthz || exit 1
          echo "Health endpoint check passed"

          curl -s http://localhost:8082/metrics || exit 1
          echo "Metrics endpoint check passed"

          echo "Successfully verified webhook manager startup"
