package:
  name: azure-workload-identity-webhook
  version: 1.5.0
  epoch: 0
  description: Mutating webhook for Azure Workload Identity
  copyright:
    - license: MIT

environment:
  environment:
    CGO_ENABLED: "0"
    GOFLAGS: "-trimpath"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/Azure/azure-workload-identity
      tag: v${{package.version}}
      expected-commit: fcb1e3f7a54da5d6c7db265c52fbe975efd7a643

  - uses: go/build
    with:
      packages: ./cmd/webhook
      output: manager
      ldflags: |-
        -X github.com/Azure/azure-workload-identity/pkg/version.BuildVersion=v${{package.version}}
        -X github.com/Azure/azure-workload-identity/pkg/version.BuildTime=$(date -u +%Y-%m-%d-%H:%M)
        -X github.com/Azure/azure-workload-identity/pkg/version.VCSVersion=$(git rev-parse --short HEAD)
        -X github.com/Azure/azure-workload-identity/pkg/webhook.ProxyImageVersion=v${{package.version}}
        -X github.com/Azure/azure-workload-identity/pkg/webhook.ProxyImageRegistry=mcr.microsoft.com/oss/azure/workload-identity

  - uses: strip

subpackages:
  - name: azure-workload-identity-webhook-compat
    description: Compatibility symlink for azure-workload-identity-webhook
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"
          ln -s /usr/bin/manager "${{targets.contextdir}}/manager"
      - runs: |
          stat /manager

update:
  enabled: true
  github:
    identifier: Azure/azure-workload-identity
    strip-prefix: v

test:
  pipeline:
    - name: "Run manager and verify help output"
      runs: |
        manager --help
