package:
  name: nifi-registry
  version: "2.4.0"
  epoch: 10
  description: Apache NiFi Registry is a registry for storing and managing shared resources such as versioned flows across one or more instances of NiFi.
  copyright:
    - license: Apache-2.0
  resources:
    cpu: 5
    memory: 2Gi
  dependencies:
    runtime:
      - bash
      - busybox
      - coreutils
      - git
      - java-common-jre
      - openjdk-21-jre
      - xmlstarlet

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - coreutils
      - git
      - libarchive-tools
      - maven
      - openjdk-21-default-jdk
      - rsync
      - unzip
      - xmlstarlet
  environment:
    MAVEN_OPTS: |
      -Xmx6g
      -XX:ReservedCodeCacheSize=2g
      -XX:+UseG1GC
      -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO
      -Daether.connector.http.retryHandler.count=5
      -Daether.connector.http.connectionMaxTtl=30
    NIFI_REGISTRY_BASE: "/opt/nifi-registry"
    NIFI_REGISTRY_HOME: "/opt/nifi-registry/nifi-registry-current"
    NIFI_REGISTRY_LOG_DIR: "/opt/nifi-registry/nifi-registry-current/logs"
    NIFI_REGISTRY_PID_DIR: "/opt/nifi-registry/nifi-registry-current/run"
    TOOLKIT_HOME: "/opt/nifi-registry/nifi-toolkit-current"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/apache/nifi
      tag: rel/nifi-${{package.version}}
      expected-commit: 65c7732e46cdfcb17afe0dd7b0a3e0956226bcbb

  - runs: |
      MAVEN_THREADS=2

      cd nifi-registry
      ../mvnw -T${MAVEN_THREADS}C clean package \
        --projects nifi-registry-assembly \
        --also-make \
        -DskipTests

      mkdir -p "${{targets.contextdir}}${NIFI_REGISTRY_HOME}"
      cd nifi-registry-assembly/target

      bsdtar -xf nifi-registry-${{package.version}}-bin.zip \
        --strip-components=1 \
        -C "${{targets.contextdir}}${NIFI_REGISTRY_HOME}"

      for d in conf logs database flow_storage work run; do
        mkdir -p "${{targets.contextdir}}${NIFI_REGISTRY_HOME}/$d"
        chmod 0755    "${{targets.contextdir}}${NIFI_REGISTRY_HOME}/$d"
      done


      mkdir -p "${{targets.contextdir}}${NIFI_REGISTRY_BASE}/scripts"
      cp /home/build/nifi-registry/nifi-registry-core/nifi-registry-docker/dockerhub/sh/*.sh \
         "${{targets.contextdir}}${NIFI_REGISTRY_BASE}/scripts/"
      chmod +x "${{targets.contextdir}}${NIFI_REGISTRY_BASE}/scripts/"*.sh

      ln -sf "${NIFI_REGISTRY_HOME}" \
             "${{targets.contextdir}}${NIFI_REGISTRY_BASE}/nifi-registry-${{package.version}}"

  - uses: strip

subpackages:
  - name: nifi-registry-toolkit
    description: "Toolkit for Apache NiFi Registry"
    dependencies:
      runtime:
        - nifi-registry
        - java-common-jre
        - openjdk-21-jre
    pipeline:
      - runs: |
          cd /home/build/nifi-registry/nifi-registry-toolkit
          ../../mvnw clean package \
            --projects nifi-registry-toolkit-assembly \
            --also-make \
            -DskipTests

          mkdir -p "${{targets.subpkgdir}}/${TOOLKIT_HOME}"
          cd nifi-registry-toolkit-assembly/target
          unzip nifi-registry-toolkit-${{package.version}}-bin.zip \
            -d "${{targets.subpkgdir}}/${TOOLKIT_HOME}"
          rm -f "${{targets.subpkgdir}}/${TOOLKIT_HOME}/bin/"*.bat
          ln -sf "${TOOLKIT_HOME}" \
                 "${{targets.subpkgdir}}/${TOOLKIT_HOME%/*}/nifi-toolkit-registry-${{package.version}}"
      - uses: strip
    test:
      pipeline:
        - runs: |
            test -d /opt/nifi-registry/nifi-toolkit-current

update:
  enabled: true
  ignore-regex-patterns:
    - -RC
    - -M
  github:
    identifier: apache/nifi
    use-tag: true
    strip-prefix: rel/nifi-
    tag-filter: rel/nifi-

test:
  environment:
    contents:
      packages:
        - java-common-jre
        - openjdk-21-jre
    environment:
      JAVA_HOME: /usr/lib/jvm/java-21-openjdk
      NIFI_REGISTRY_BASE: /opt/nifi-registry
      NIFI_REGISTRY_HOME: /opt/nifi-registry/nifi-registry-current
      TOOLKIT_HOME: /opt/nifi-registry/nifi-toolkit-current
      NIFI_REGISTRY_PID_DIR: /opt/nifi-registry/nifi-registry-current/run
      NIFI_REGISTRY_LOG_DIR: /opt/nifi-registry/nifi-registry-current/logs
  pipeline:
    - uses: test/daemon-check-output
      with:
        start: /opt/nifi-registry/scripts/start.sh start
        expected_output: |
          Started Server on
          Successfully initiated communication with Bootstrap
          Started Application
        timeout: 60
