package:
  name: rabbitmq-default-user-credential-updater
  version: "1.0.5"
  epoch: 4
  description: Updates RabbitMQ default user password
  copyright:
    - license: MPL-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rabbitmq/default-user-credential-updater
      tag: v${{package.version}}
      expected-commit: d4c3c4747b67c567a2d65e82b2c966566f973996

  - uses: go/build
    with:
      packages: .
      output: default-user-credential-updater

  - uses: strip

update:
  enabled: true
  github:
    identifier: rabbitmq/default-user-credential-updater
    strip-prefix: v

subpackages:
  - name: ${{package.name}}-compat
    description: Compat package for ${{package.name}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"
          ln -sf /usr/bin/default-user-credential-updater "${{targets.contextdir}}"/default-user-credential-updater
    test:
      pipeline:
        - runs: "[ \"$(stat -c '%N' /default-user-credential-updater 2>/dev/null)\" = \"'/default-user-credential-updater' -> '/usr/bin/default-user-credential-updater'\" ]"

  - name: ${{package.name}}-bitnami-compat
    description: "Bitnami compatibility package for ${{package.name}}"
    dependencies:
      runtime:
        - bash
        - procps
        - ca-certificates-bundle
        - merged-usrsbin
        - wolfi-baselayout
    pipeline:
      - uses: bitnami/compat
        with:
          image: rmq-default-credential-updater
          version-path: "1/debian-12"
      - runs: |
          # Make directory structure
          mkdir -p "${{targets.subpkgdir}}"/opt/bitnami/rmq-default-credential-updater/bin

          # Set up binary symlink
          ln -sf /usr/bin/default-user-credential-updater "${{targets.subpkgdir}}"/opt/bitnami/rmq-default-credential-updater/bin/default-user-credential-updater

          # Handle license
          mkdir -p "${{targets.subpkgdir}}"/opt/bitnami/rmq-default-credential-updater/licenses
          cp LICENSE "${{targets.subpkgdir}}"/opt/bitnami/rmq-default-credential-updater/licenses/LICENSE

          # Remove conflicting certificates to avoid collision with ca-certificates-bundle
          rm -rf "${{targets.subpkgdir}}"/etc/ssl/certs/ca-certificates.crt
    test:
      environment:
        contents:
          packages:
            - ${{package.name}}
            - ca-certificates-bundle
      pipeline:
        - runs: |
            [ "$(stat -c '%N' /opt/bitnami/rmq-default-credential-updater/bin/default-user-credential-updater 2>/dev/null)" = "'/opt/bitnami/rmq-default-credential-updater/bin/default-user-credential-updater' -> '/usr/bin/default-user-credential-updater'" ]
            [ -d "/opt/bitnami/rmq-default-credential-updater/licenses" ]
            [ -f "/opt/bitnami/rmq-default-credential-updater/licenses/LICENSE" ]

test:
  pipeline:
    - runs: |
        default-user-credential-updater -h  2>&1 | grep "Usage of default-user-credential-updater:"
        default-user-credential-updater version
        default-user-credential-updater --help
