package:
  name: redis-operator
  version: "0.18.1"
  epoch: 1
  description: "A Kubernetes operator to manage Redis clusters"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - ca-certificates-bundle
      - wolfi-base
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: "https://github.com/OT-CONTAINER-KIT/redis-operator.git"
      tag: "v${{package.version}}"
      expected-commit: "c48c9c5b0d09fb3e3438e269c7b5457585d062c2"

  - uses: go/build
    with:
      packages: "."
      output: "manager"
      ldflags: "-s -w"
      prefix: "usr"
      install-dir: "bin"
      tidy: true

  - uses: strip

update:
  enabled: true
  github:
    identifier: "OT-CONTAINER-KIT/redis-operator"
    strip-prefix: "v"

test:
  pipeline:
    - name: "Verify redis-operator binary"
      runs: |
        /usr/bin/manager -help
